### PR TITLE
- Moved the timer label to the .h file to be able to access it globally

### PR DESCRIPTION
**Pull request by ghost**
I needed this to change the color of the text in my project.

### CODE REVIEW

**Comment by jeffkibuule** [comment]
Hey @pyraego,

I think there's this approach of directly exposing the label (which may be too much, you have the power to do and change everything about the label), or having setters for each of the different color states. I'm thinking the latter is probably better. Would that be enough for your project?

Also, thanks for actually using it! It's my first open-source project. :)

**Comment by ghost** [comment]
Yea that would be enough. Thank again for this plugin! Building an application around this plugin. I will create more pull requests for any other modifications I make.

**Comment by jeffkibuule** [comment]
@pyraego Ended up exposing the label's textColor in v0.2.2. Hopefully that'll work. See this commit: https://github.com/jeffkibuule/JSKTimerView/commit/07ca928d530723516297eed080546cfa58f81bf9

**Comment by ghost** [comment]
Thanks again for the update!

**Pull request closed without merging**
